-- ad-fontes accounts + compounding study memory schema.
--
-- Run this once in your Supabase project's SQL Editor (Dashboard -> SQL
-- Editor -> New query -> paste this whole file -> Run). Safe to re-run:
-- every statement is idempotent (IF NOT EXISTS / OR REPLACE), so running it
-- again after a partial failure or a later addition won't error out on
-- what's already there.
--
-- Design notes:
--
-- - `profiles` extends Supabase's built-in `auth.users` (which Auth owns
--   and which isn't exposed on the API) with the columns *this app* needs.
--   Kept minimal on purpose: just enough to have a row per user to build on
--   later (e.g. subscription status, once the billing work starts) without
--   speculatively adding Stripe-shaped columns before that design happens.
-- - `study_entries` is the compounding study memory: one row per passage
--   Claude actually gathered during a signed-in user's conversation. This
--   is what lets Claude later say "you looked at this same word study back
--   in March" -- see lib/chat.js's search_study_history tool.
-- - The server (lib/supabase.js) always talks to Postgres using the
--   *secret* key, which bypasses RLS entirely (that's what the secret key
--   is for -- see https://supabase.com/docs/guides/getting-started/api-keys).
--   The RLS policies below are still worth having as defense-in-depth, in
--   case a future client-side feature ever queries Postgres directly with
--   the user's own session instead of going through this app's server.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

-- Added after profiles first shipped -- `alter ... add column if not
-- exists` rather than folding into the create table above, so this file
-- stays safe to re-run against a project that already has the original
-- profiles table (see this file's own header comment on idempotency).
-- Defaults to false: the daily digest email (see lib/daily-digest.js) is
-- opt-in, not opt-out -- nobody gets emailed just for signing up.
alter table public.profiles
  add column if not exists daily_digest_opt_in boolean not null default false;

-- Minimal paid tier (see README -> Subscription / paid tier): there's no
-- real checkout wired up yet, so this is set by hand in the Supabase
-- dashboard's Table Editor for now, not by any code path in this app.
-- Everything already built stays free; the only thing this currently gates
-- is naming your agent (agent_name below, and lib/chat.js's use of it).
alter table public.profiles
  add column if not exists is_paid boolean not null default false;

-- Paid-only: a display name for the AI agent, purely cosmetic (used in the
-- chat system prompt -- see lib/chat.js) to make conversations feel a
-- little more personal. Null/empty means "use the default persona." Not
-- enforced server-side that only paid accounts can set this (PostgREST has
-- no notion of that without a stored procedure) -- server.js's
-- handleSetPreferences is what actually gates the write on is_paid.
alter table public.profiles
  add column if not exists agent_name text;

alter table public.profiles enable row level security;

drop policy if exists "profiles: users can read their own row" on public.profiles;
create policy "profiles: users can read their own row"
  on public.profiles for select
  using (auth.uid() = id);

-- Auto-creates a profiles row the moment someone signs up, so the app
-- never has to remember to do it itself (and can't forget to on some
-- code path and end up with a user who has no profile row).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create table if not exists public.study_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reference text,      -- USFM, e.g. "JHN.3.16" -- null for a topical/lexicon-only entry
  topic text,           -- e.g. a search_lexicon keyword, when there's no single reference
  summary text not null, -- a short gist of what was studied -- see lib/chat.js for how this gets written
  created_at timestamptz not null default now()
);

create index if not exists study_entries_user_id_created_at_idx
  on public.study_entries (user_id, created_at desc);

-- Plain trigram-free full-text-ish search over topic/summary is enough for
-- v1 (search_study_history matches on reference OR a keyword substring) --
-- see lib/supabase.js. Not using pgvector/embeddings yet; flagged as a
-- natural v2 upgrade once there's real usage to justify the extra
-- infrastructure and per-entry embedding cost.
create index if not exists study_entries_summary_search_idx
  on public.study_entries using gin (to_tsvector('english', coalesce(summary, '') || ' ' || coalesce(topic, '')));

alter table public.study_entries enable row level security;

drop policy if exists "study_entries: users can read their own rows" on public.study_entries;
create policy "study_entries: users can read their own rows"
  on public.study_entries for select
  using (auth.uid() = user_id);

drop policy if exists "study_entries: users can insert their own rows" on public.study_entries;
create policy "study_entries: users can insert their own rows"
  on public.study_entries for insert
  with check (auth.uid() = user_id);

-- One row per conversation for a signed-in user, so the "previous
-- conversations" menu has something durable to list even after the
-- session's live back-and-forth (lib/session-store.js, a 2-hour idle TTL in
-- Redis) has expired. `id` is the app's own session id (a client-generated
-- UUID -- see lib/chat.js's chatTurn), not a separately generated one, so a
-- resumed conversation keeps writing to the same row instead of forking a
-- new one. `render_log` mirrors the frontend's own lightweight message
-- shape (public/app.js's chatLogData: { role, text, gathered? }) rather
-- than the raw Anthropic message format (which includes tool_use/
-- tool_result blocks) -- simple to append to, and exactly what the UI needs
-- to redraw a past conversation. Note this means resuming an old
-- conversation whose Redis session already expired shows the full past
-- transcript, but the *next* message starts a fresh model context under the
-- same conversation id -- Claude won't have the old back-and-forth as live
-- context, only what search_study_history can surface. A known v2 upgrade
-- would be persisting the raw Anthropic-format history here too.
create table if not exists public.conversations (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text,
  primary_book text,          -- USFM book code (e.g. "JHN") of the first passage gathered, if any -- lib/bible-books.js
  render_log jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists conversations_user_id_updated_at_idx
  on public.conversations (user_id, updated_at desc);

alter table public.conversations enable row level security;

drop policy if exists "conversations: users can read their own rows" on public.conversations;
create policy "conversations: users can read their own rows"
  on public.conversations for select
  using (auth.uid() = user_id);

drop policy if exists "conversations: users can insert their own rows" on public.conversations;
create policy "conversations: users can insert their own rows"
  on public.conversations for insert
  with check (auth.uid() = user_id);

drop policy if exists "conversations: users can update their own rows" on public.conversations;
create policy "conversations: users can update their own rows"
  on public.conversations for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- A signed-in user's own notes on a passage -- distinct from study_entries
-- (which is Claude's own log of what it looked up, used for
-- search_study_history) in that a note is something the *user* wrote
-- themselves, verbatim, and expects to see again unchanged. `reference` is
-- the same USFM-ish string gatherPassage works with (e.g. "JHN.3.16"),
-- matching exactly rather than fuzzily -- notes on "JHN.3.16" and
-- "JHN.3.16-18" are treated as separate references, same as the app treats
-- them as separate gathered passages. bigint identity (not uuid) since,
-- unlike conversations, nothing client-side ever needs to generate this id
-- itself before the row exists.
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reference text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The lookup this feature actually does on every passage view: "does this
-- user have notes on this exact reference." created_at DESC within that so
-- multiple notes on the same passage show oldest-first... actually newest
-- first reads better for "what did I just jot down," hence DESC here too.
create index if not exists notes_user_id_reference_idx
  on public.notes (user_id, reference, created_at desc);

alter table public.notes enable row level security;

drop policy if exists "notes: users can read their own rows" on public.notes;
create policy "notes: users can read their own rows"
  on public.notes for select
  using (auth.uid() = user_id);

drop policy if exists "notes: users can insert their own rows" on public.notes;
create policy "notes: users can insert their own rows"
  on public.notes for insert
  with check (auth.uid() = user_id);

drop policy if exists "notes: users can delete their own rows" on public.notes;
create policy "notes: users can delete their own rows"
  on public.notes for delete
  using (auth.uid() = user_id);

-- Saved sermon/lesson outlines -- a Pro feature (see README -> Subscription
-- / paid tier), same shape/reasoning as `notes` (reference + user-authored
-- text a specific person chose to keep), plus a `title` column notes don't
-- have, since an outline is meant to be found again by name later ("My
-- Outlines" page) rather than just by the passage it's on. Unlike notes,
-- which are created directly from a form, a row here is created by the
-- user explicitly saving one specific chat reply (see server.js's POST
-- /api/outlines) -- there's no auto-save of every sermon-outline-mode
-- reply, since not every one is a keeper.
create table if not exists public.outlines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reference text,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

-- The lookup this feature actually does: "list this user's saved outlines,
-- newest first" -- unlike notes there's no per-reference lookup, so no
-- reference column in this index.
create index if not exists outlines_user_id_created_at_idx
  on public.outlines (user_id, created_at desc);

alter table public.outlines enable row level security;

drop policy if exists "outlines: users can read their own rows" on public.outlines;
create policy "outlines: users can read their own rows"
  on public.outlines for select
  using (auth.uid() = user_id);

drop policy if exists "outlines: users can insert their own rows" on public.outlines;
create policy "outlines: users can insert their own rows"
  on public.outlines for insert
  with check (auth.uid() = user_id);

drop policy if exists "outlines: users can delete their own rows" on public.outlines;
create policy "outlines: users can delete their own rows"
  on public.outlines for delete
  using (auth.uid() = user_id);

-- Per-user progress through one of the curated reading plans defined in
-- lib/reading-plans.js. `plan_id` is a plain text foreign key to that
-- file's static `id` field, not a real foreign key constraint -- the plan
-- list lives in code, not a database table (same reasoning as
-- lib/daily-passage.js's DAILY_PASSAGES: curated content, versioned with
-- the app, no admin UI needed), so there's nothing in Postgres for it to
-- reference. `completed_days` is a plain integer array rather than a
-- separate one-row-per-completed-day table: a reading plan here is capped
-- at a handful of days (see lib/reading-plans.js), so there's no scale
-- concern that would justify the extra join, and the whole array is always
-- read/written together (see lib/supabase.js's setReadingPlanDayComplete)
-- rather than queried day-by-day.
create table if not exists public.reading_plan_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  plan_id text not null,
  completed_days integer[] not null default '{}',
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, plan_id)
);

create index if not exists reading_plan_progress_user_id_idx
  on public.reading_plan_progress (user_id);

alter table public.reading_plan_progress enable row level security;

drop policy if exists "reading_plan_progress: users can read their own rows" on public.reading_plan_progress;
create policy "reading_plan_progress: users can read their own rows"
  on public.reading_plan_progress for select
  using (auth.uid() = user_id);

drop policy if exists "reading_plan_progress: users can insert their own rows" on public.reading_plan_progress;
create policy "reading_plan_progress: users can insert their own rows"
  on public.reading_plan_progress for insert
  with check (auth.uid() = user_id);

drop policy if exists "reading_plan_progress: users can update their own rows" on public.reading_plan_progress;
create policy "reading_plan_progress: users can update their own rows"
  on public.reading_plan_progress for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "reading_plan_progress: users can delete their own rows" on public.reading_plan_progress;
create policy "reading_plan_progress: users can delete their own rows"
  on public.reading_plan_progress for delete
  using (auth.uid() = user_id);

-- Ensure service_role (used server-side via SUPABASE_SECRET_KEY, meant to
-- bypass RLS entirely) actually has standing privileges on every table in
-- the public schema, and will automatically get them on any table created
-- here in the future too. Safe/idempotent to re-run. This closes off the
-- class of permission-denied error that surfaced when is_paid/agent_name
-- were added by hand without a matching grant.
grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant all on sequences to service_role;
