-- ad-fontes accounts + compounding study memory schema.
--
-- Run this once in your Supabase project's SQL Editor (Dashboard -> SQL
-- Editor -> New query -> paste this whole file -> Run). Safe to re-run:
-- every statement is idempotent (IF NOT EXISTS / OR REPLACE), so running it
-- again after a partial failure or a later addition won't error out on
-- what's already there.
--
-- Design notes:
--
-- - `profiles` extends Supabase's built-in `auth.users` (which Auth owns
--   and which isn't exposed on the API) with the columns *this app* needs.
--   Kept minimal on purpose: just enough to have a row per user to build on
--   later (e.g. subscription status, once the billing work starts) without
--   speculatively adding Stripe-shaped columns before that design happens.
-- - `study_entries` is the compounding study memory: one row per passage
--   Claude actually gathered during a signed-in user's conversation. This
--   is what lets Claude later say "you looked at this same word study back
--   in March" -- see lib/chat.js's search_study_history tool.
-- - The server (lib/supabase.js) always talks to Postgres using the
--   *secret* key, which bypasses RLS entirely (that's what the secret key
--   is for -- see https://supabase.com/docs/guides/getting-started/api-keys).
--   The RLS policies below are still worth having as defense-in-depth, in
--   case a future client-side feature ever queries Postgres directly with
--   the user's own session instead of going through this app's server.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles: users can read their own row" on public.profiles;
create policy "profiles: users can read their own row"
  on public.profiles for select
  using (auth.uid() = id);

-- Auto-creates a profiles row the moment someone signs up, so the app
-- never has to remember to do it itself (and can't forget to on some
-- code path and end up with a user who has no profile row).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create table if not exists public.study_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reference text,      -- USFM, e.g. "JHN.3.16" -- null for a topical/lexicon-only entry
  topic text,           -- e.g. a search_lexicon keyword, when there's no single reference
  summary text not null, -- a short gist of what was studied -- see lib/chat.js for how this gets written
  created_at timestamptz not null default now()
);

create index if not exists study_entries_user_id_created_at_idx
  on public.study_entries (user_id, created_at desc);

-- Plain trigram-free full-text-ish search over topic/summary is enough for
-- v1 (search_study_history matches on reference OR a keyword substring) --
-- see lib/supabase.js. Not using pgvector/embeddings yet; flagged as a
-- natural v2 upgrade once there's real usage to justify the extra
-- infrastructure and per-entry embedding cost.
create index if not exists study_entries_summary_search_idx
  on public.study_entries using gin (to_tsvector('english', coalesce(summary, '') || ' ' || coalesce(topic, '')));

alter table public.study_entries enable row level security;

drop policy if exists "study_entries: users can read their own rows" on public.study_entries;
create policy "study_entries: users can read their own rows"
  on public.study_entries for select
  using (auth.uid() = user_id);

drop policy if exists "study_entries: users can insert their own rows" on public.study_entries;
create policy "study_entries: users can insert their own rows"
  on public.study_entries for insert
  with check (auth.uid() = user_id);

-- One row per conversation for a signed-in user, so the "previous
-- conversations" menu has something durable to list even after the
-- session's live back-and-forth (lib/session-store.js, a 2-hour idle TTL in
-- Redis) has expired. `id` is the app's own session id (a client-generated
-- UUID -- see lib/chat.js's chatTurn), not a separately generated one, so a
-- resumed conversation keeps writing to the same row instead of forking a
-- new one. `render_log` mirrors the frontend's own lightweight message
-- shape (public/app.js's chatLogData: { role, text, gathered? }) rather
-- than the raw Anthropic message format (which includes tool_use/
-- tool_result blocks) -- simple to append to, and exactly what the UI needs
-- to redraw a past conversation. Note this means resuming an old
-- conversation whose Redis session already expired shows the full past
-- transcript, but the *next* message starts a fresh model context under the
-- same conversation id -- Claude won't have the old back-and-forth as live
-- context, only what search_study_history can surface. A known v2 upgrade
-- would be persisting the raw Anthropic-format history here too.
create table if not exists public.conversations (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text,
  primary_book text,          -- USFM book code (e.g. "JHN") of the first passage gathered, if any -- lib/bible-books.js
  render_log jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists conversations_user_id_updated_at_idx
  on public.conversations (user_id, updated_at desc);

alter table public.conversations enable row level security;

drop policy if exists "conversations: users can read their own rows" on public.conversations;
create policy "conversations: users can read their own rows"
  on public.conversations for select
  using (auth.uid() = user_id);

drop policy if exists "conversations: users can insert their own rows" on public.conversations;
create policy "conversations: users can insert their own rows"
  on public.conversations for insert
  with check (auth.uid() = user_id);

drop policy if exists "conversations: users can update their own rows" on public.conversations;
create policy "conversations: users can update their own rows"
  on public.conversations for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- A signed-in user's own notes on a passage -- distinct from study_entries
-- (which is Claude's own log of what it looked up, used for
-- search_study_history) in that a note is something the *user* wrote
-- themselves, verbatim, and expects to see again unchanged. `reference` is
-- the same USFM-ish string gatherPassage works with (e.g. "JHN.3.16"),
-- matching exactly rather than fuzzily -- notes on "JHN.3.16" and
-- "JHN.3.16-18" are treated as separate references, same as the app treats
-- them as separate gathered passages. bigint identity (not uuid) since,
-- unlike conversations, nothing client-side ever needs to generate this id
-- itself before the row exists.
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reference text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The lookup this feature actually does on every passage view: "does this
-- user have notes on this exact reference." created_at DESC within that so
-- multiple notes on the same passage show oldest-first... actually newest
-- first reads better for "what did I just jot down," hence DESC here too.
create index if not exists notes_user_id_reference_idx
  on public.notes (user_id, reference, created_at desc);

alter table public.notes enable row level security;

drop policy if exists "notes: users can read their own rows" on public.notes;
create policy "notes: users can read their own rows"
  on public.notes for select
  using (auth.uid() = user_id);

drop policy if exists "notes: users can insert their own rows" on public.notes;
create policy "notes: users can insert their own rows"
  on public.notes for insert
  with check (auth.uid() = user_id);

drop policy if exists "notes: users can delete their own rows" on public.notes;
create policy "notes: users can delete their own rows"
  on public.notes for delete
  using (auth.uid() = user_id);
