-- ad-fontes accounts + compounding study memory schema.
--
-- Run this once in your Supabase project's SQL Editor (Dashboard -> SQL
-- Editor -> New query -> paste this whole file -> Run). Safe to re-run:
-- every statement is idempotent (IF NOT EXISTS / OR REPLACE), so running it
-- again after a partial failure or a later addition won't error out on
-- what's already there.
--
-- Design notes:
--
-- - `profiles` extends Supabase's built-in `auth.users` (which Auth owns
--   and which isn't exposed on the API) with the columns *this app* needs.
--   Kept minimal on purpose: just enough to have a row per user to build on
--   later (e.g. subscription status, once the billing work starts) without
--   speculatively adding Stripe-shaped columns before that design happens.
-- - `study_entries` is the compounding study memory: one row per passage
--   Claude actually gathered during a signed-in user's conversation. This
--   is what lets Claude later say "you looked at this same word study back
--   in March" -- see lib/chat.js's search_study_history tool.
-- - The server (lib/supabase.js) always talks to Postgres using the
--   *secret* key, which bypasses RLS entirely (that's what the secret key
--   is for -- see https://supabase.com/docs/guides/getting-started/api-keys).
--   The RLS policies below are still worth having as defense-in-depth, in
--   case a future client-side feature ever queries Postgres directly with
--   the user's own session instead of going through this app's server.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles: users can read their own row" on public.profiles;
create policy "profiles: users can read their own row"
  on public.profiles for select
  using (auth.uid() = id);

-- Auto-creates a profiles row the moment someone signs up, so the app
-- never has to remember to do it itself (and can't forget to on some
-- code path and end up with a user who has no profile row).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create table if not exists public.study_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reference text,      -- USFM, e.g. "JHN.3.16" -- null for a topical/lexicon-only entry
  topic text,           -- e.g. a search_lexicon keyword, when there's no single reference
  summary text not null, -- a short gist of what was studied -- see lib/chat.js for how this gets written
  created_at timestamptz not null default now()
);

create index if not exists study_entries_user_id_created_at_idx
  on public.study_entries (user_id, created_at desc);

-- Plain trigram-free full-text-ish search over topic/summary is enough for
-- v1 (search_study_history matches on reference OR a keyword substring) --
-- see lib/supabase.js. Not using pgvector/embeddings yet; flagged as a
-- natural v2 upgrade once there's real usage to justify the extra
-- infrastructure and per-entry embedding cost.
create index if not exists study_entries_summary_search_idx
  on public.study_entries using gin (to_tsvector('english', coalesce(summary, '') || ' ' || coalesce(topic, '')));

alter table public.study_entries enable row level security;

drop policy if exists "study_entries: users can read their own rows" on public.study_entries;
create policy "study_entries: users can read their own rows"
  on public.study_entries for select
  using (auth.uid() = user_id);

drop policy if exists "study_entries: users can insert their own rows" on public.study_entries;
create policy "study_entries: users can insert their own rows"
  on public.study_entries for insert
  with check (auth.uid() = user_id);
